// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intimate.files;

import com.intimate.files.File;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect File_Roo_Configurable {
    
    declare @type: File: @Configurable;
    
}
