// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intimate.owners.groups;

import com.intimate.owners.groups.RoomOwnerGroup;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RoomOwnerGroup_Roo_Configurable {
    
    declare @type: RoomOwnerGroup: @Configurable;
    
}
