// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intimate.rooms.activities.contents;

import com.intimate.rooms.activities.contents.Content;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Content_Roo_Configurable {
    
    declare @type: Content: @Configurable;
    
}
